# Generated by Django 4.2.2 on 2023-06-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apaterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('amaterno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('hora', models.DateTimeField()),
                ('comentario', models.TextField(max_length=200, verbose_name='Comentario')),
            ],
        ),
    ]
