# Generated by Django 4.2.2 on 2023-06-28 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_formulario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formulario',
            new_name='Project',
        ),
    ]
