# Generated by Django 4.2.2 on 2023-06-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_formulario_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='static/img', verbose_name='imagen')),
            ],
        ),
    ]
